name: GLaDOS-Signin

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 */3 * * *

jobs:
  GLaDOS-Signin:
    runs-on: ubuntu-latest
    env:
      COOKIE: ${{ secrets.COOKIE }}
      Random: ${{ secrets.Random }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set script permissions
        run: chmod +x signin.sh
      
      - name: signin
        run: |
          OUTPUT=$(./signin.sh)
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
